feat: Read from files

diff --git a/src/shadow b/src/shadow
--- a/src/shadow
+++ b/src/shadow
@@ -17,11 +17,12 @@ $(_text "$BLUE" "Usage:")
   shadow FLAG <FLAG_INPUT> COMMANDS
 
 $(_text "$BLUE" "Flags:")
-  -h      Displays this message and exits
+  -h         Displays this message and exits
+  -j <JOBS>  Run with async. Default is 0.
 EOF
 }
 
-run_commands() {
+executeCommands() {
   local result=0
   local i=0
   local curr_dir
@@ -75,31 +76,36 @@ run_commands() {
   done
 }
 
-main() {
+run_commands() {
+  local directory=$1
+  if [[ ! -d "$directory" ]]; then
+    echo "Directory '$directory' not found."
+    return 1
+  fi
+  pushd "$directory" >/dev/null || return 1
   if [ "$PARALLELS" -gt 0 ]; then
-    for directory in "${directories[@]}"; do
-      if [[ ! -d "$directory" ]]; then
-        echo "Directory '$directory' not found."
-        continue
-      fi
-      pushd "$directory" >/dev/null || return 1
-      run_commands &
-      popd >/dev/null || return 1
-      while [ "$(jobs | wc -l)" -eq "$PARALLELS" ]; do
-        wait -n
-      done
-    done
+    executeCommands &
   else
-    for directory in "${directories[@]}"; do
-      if [[ ! -d "$directory" ]]; then
-        echo "Directory '$directory' not found."
-        continue
-      fi
-      pushd "$directory" >/dev/null || return 1
-      run_commands
-      popd >/dev/null || return 1
+    executeCommands
+  fi
+  popd >/dev/null || return 1
+  if [ "$PARALLELS" -gt 0 ]; then
+    while [ "$(jobs | wc -l)" -eq "$PARALLELS" ]; do
+      wait -n
     done
   fi
+}
+
+main() {
+  for directory in "${directories[@]}"; do
+    if [ -f "$directory" ]; then
+      cat "$directory" | while IFS= read -r dir; do
+        run_commands "$dir"
+      done
+    else
+      run_commands "$directory"
+    fi
+  done
 }
 
 case "$1" in
