feat: Add builtin async feature

diff --git a/src/shadow b/src/shadow
--- a/src/shadow
+++ b/src/shadow
@@ -1,6 +1,7 @@
 #!/usr/bin/env bash
 
 directories=()
+PARALLELS=0
 
 RED="$(tput setaf 196)"
 GREEN="$(tput setaf 82)"
@@ -75,15 +76,30 @@ run_commands() {
 }
 
 main() {
-  for directory in "${directories[@]}"; do
-    if [[ ! -d "$directory" ]]; then
-      echo "Directory '$directory' not found."
-      continue
-    fi
-    pushd "$directory" >/dev/null || return 1
-    run_commands
-    popd >/dev/null || return 1
-  done
+  if [ "$PARALLELS" -gt 0 ]; then
+    for directory in "${directories[@]}"; do
+      if [[ ! -d "$directory" ]]; then
+        echo "Directory '$directory' not found."
+        continue
+      fi
+      pushd "$directory" >/dev/null || return 1
+      run_commands &
+      popd >/dev/null || return 1
+      while [ "$(jobs | wc -l)" -eq "$PARALLELS" ]; do
+        wait -n
+      done
+    done
+  else
+    for directory in "${directories[@]}"; do
+      if [[ ! -d "$directory" ]]; then
+        echo "Directory '$directory' not found."
+        continue
+      fi
+      pushd "$directory" >/dev/null || return 1
+      run_commands
+      popd >/dev/null || return 1
+    done
+  fi
 }
 
 case "$1" in
@@ -97,7 +113,7 @@ case "$1" in
   ;;
 esac
 
-while getopts ":h-" opt; do
+while getopts ":h-j:" opt; do
   case "$opt" in
   h)
     help
@@ -105,6 +121,9 @@ while getopts ":h-" opt; do
     ;;
   -)
     break
+    ;;
+  j)
+    PARALLELS=$OPTARG
     ;;
   ?)
     echo "${RED}ERROR:${RESET} Invalid option '-$OPTARG'" >&2
